import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(__dirname, "../package.json");
const versionPath = resolve(__dirname, "../src/generated/version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
const version = pkg.version ?? "0.0.0";

const content = `// Generated by scripts/generate-version.mjs -- do not edit manually
export const ENGINE_VERSION = ${JSON.stringify(version)};
`;

writeFileSync(versionPath, content, "utf-8");
console.log(`Generated version.ts: ${version}`);
