import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const dataDir = resolve(root, "data");
const generatedDir = resolve(root, "src/generated");

if (!existsSync(generatedDir)) {
  mkdirSync(generatedDir, { recursive: true });
}

function loadJSON(filePath) {
  return JSON.parse(readFileSync(filePath, "utf-8"));
}

function writeGeneratedFile(name, jsonData) {
  const tsPath = resolve(generatedDir, `${name}.ts`);
  const json = JSON.stringify(jsonData, null, 2);
  const content = `// Generated by scripts/generate-data.mjs from ${name}.json -- do not edit manually
const data: unknown = ${json};
export default data;
`;
  writeFileSync(tsPath, content, "utf-8");
  try {
    execSync(`prettier --write "${tsPath}"`, { stdio: "pipe" });
  } catch {
    // prettier may not be available; skip formatting
  }
  console.log(`Generated src/generated/${name}.ts`);
}

const dataFiles = [
  { name: "models", file: "models.json" },
  { name: "quantizations", file: "quantizations.json" },
  { name: "assumptions", file: "assumptions.json" },
];

for (const df of dataFiles) {
  const jsonPath = resolve(dataDir, df.file);
  if (existsSync(jsonPath)) {
    const data = loadJSON(jsonPath);
    writeGeneratedFile(df.name, data);
  } else {
    console.error(`Data file not found: ${jsonPath}`);
    process.exitCode = 1;
  }
}
